 /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 grog_the_adventurer.glb 
Author: kaimueri (https://sketchfab.com/kaimueri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grog-the-adventurer-6851846538614cb7a1cb1178ed7b46d4
Title: Grög the Adventurer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/grog_the_adventurer.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.116}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.ID_Flask} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.ID_Flask} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.ID_Flask} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.ID_Flask} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.ID_Flask} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.ID_Flask} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Pupils} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Pupils} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.EyesHighLight} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.EyesHighLight} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Drops} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.ID_Rocksack} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_76.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_84.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_86.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_88.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_90.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.ID_Frog} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.ID_Frog} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/grog_the_adventurer.glb')
