/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 marvel_rivals_-_batman_beyond_fanart.glb 
Author: Andrea Patrik (https://sketchfab.com/ulbabrab94)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/marvel-rivals-batman-beyond-fanart-7c55f34bb390495989dec0ff4257ed40
Title: Marvel Rivals - Batman Beyond FanArt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/marvel_rivals_-_batman_beyond_fanart.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Helmet_Low_Batman_Helmet_0.geometry} material={materials.Batman_Helmet} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Helmet_Neck_Low_Batman_Helmet_0.geometry} material={materials.Batman_Helmet} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Helmet_Respiretor_Low_Batman_Helmet_0.geometry} material={materials.Batman_Helmet} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Helmet_Forehead_Low_Batman_Helmet_0.geometry} material={materials.Batman_Helmet} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Helmet_Jaw_Low_Batman_Helmet_0.geometry} material={materials.Batman_Helmet} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Outline_Helmet_Outline_0.geometry} material={materials.Outline} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Low_Batman_Body_0.geometry} material={materials.Batman_Body} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Arm_Fold_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Knuckles_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Fingers_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Gloves_Plate_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Calf_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Knee_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Body_Belt_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Shouders_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Shouders_Vent_Low_Batman_Armor_0.geometry} material={materials.Batman_Armor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cape_Batman_Cape_0.geometry} material={materials.Batman_Cape} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.lowpoly_teeth_Teeth_0.geometry} material={materials.Teeth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Outline_Body_Outline_0.geometry} material={materials.Outline} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/marvel_rivals_-_batman_beyond_fanart.glb')
