/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 r.e.p.o_realistic_character_free_download.glb 
Author: Tijmen Zwaneveld (https://sketchfab.com/TijmenZwaneveld)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/repo-realistic-character-free-download-7394f098116f4734b8f7a684af862b39
Title: R.E.P.O "Realistic" Character *FREE DOWNLOAD*
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/model/r.e.p.o_realistic_character_free_download.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="40eda4e05b66473fbf3a198ef3bac52cfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Repo">
                  <group name="Object_5">
                    <group name="Hips_Controller" position={[0, 38.457, 0]} rotation={[Math.PI / 2, -0.002, 0]}>
                      <group name="Torso_Controller" position={[0, 0, -27.223]} rotation={[-0.001, 0.006, 0.217]}>
                        <group name="Arm_L_Controller" position={[45.873, 0, 30.472]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
                        <group name="Arm_R_Controller" position={[-40.03, 0, 23.836]} rotation={[0, 1.565, Math.PI / 2]} />
                        <group name="Torso_2_Controller" position={[0, 0, -31.782]} rotation={[-0.003, 0.009, 0.187]}>
                          <group name="Neck_Controller" position={[0, -21.885, -10.172]} rotation={[0.536, -0.02, 2.926]}>
                            <group name="Eye_L_Controller" position={[16.088, -20.419, -30.73]} rotation={[-0.982, -0.673, 0.119]} />
                            <group name="Eye_L_Controller_2" position={[-5.667, -25.334, -30.92]} rotation={[-0.995, -0.581, 0.112]} />
                          </group>
                        </group>
                      </group>
                    </group>
                    <primitive object={nodes._rootJoint} />
                    <group name="Leg_R_Controller" position={[-9.507, -1.401, 0]} rotation={[-Math.PI / 2, 0.002, 0]} />
                    <group name="Leg_L_Controller" position={[9.507, -1.401, 0]} rotation={[-Math.PI / 2, -0.002, 0]} />
                    <group name="RePo_Character">
                      <group name="Repo_2" />
                    </group>
                    <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Scene_-_Root']} skeleton={nodes.Object_7.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/r.e.p.o_realistic_character_free_download.glb')
